CREATE DATABASE SOLVE;

USE SOLVE;

CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(150),
AUTHOR VARCHAR(300),
GENER VARCHAR (200),
PRICE INT,
PUBLISHED_YEAR YEAR,
IN_STOCK BOOLEAN
);

INSERT INTO BOOKS (BOOK_ID, TITLE, AUTHOR, GENER, PRICE, PUBLISHED_YEAR, IN_STOCK) VALUES
(1,'IT ENDS WITH US','HELEN','FICTIONAL',250,1999,TRUE),
(2,'IT STARTS WITH US','HELEN','FICTIONAL',250,2000,FALSE),
(3,'PERFECT QUESTION PERFECT ANSWER','BHAKTHI VEDHANTHA BOOK TRUST','SPIRITUAL',100,1997,TRUE);

SELECT* FROM BOOKS;
SELECT TITLE, AUTHOR, GENER, PRICE FROM BOOKS;