CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
SALLARY INT
);

INSERT INTO EMPLOYEES VALUES
(120,'BINDU');

SELECT * FROM EMPLOYEES;

INSERT INTO EMPLOYEES(EMPLOYEE_ID,NAME) VALUES
(120,'BINDU');

CREATE TABLE USERS(
USER_ID INT PRIMARY KEY,
USERNAME VARCHAR(100) UNIQUE
);

INSERT INTO USERS VALUES
(100,'BINDU');
SELECT* FROM USERS;

INSERT INTO USERS VALUES
(200,'BINDU');

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY,
ORDER_DATE DATE DEFAULT '2025-08-22'
);

INSERT INTO ORDERS VALUES
(100,'2024-08-21');

SELECT*FROM ORDERS;

INSERT INTO ORDERS (ORDER_ID,ORDER_DATE) VALUES
(200, default);

use movies;


create table products(
product_id int primary key,
price int,
quantity int check(quantity>=0)
);

insert into products values
(2,200,-1);

insert into products values
(2,200,3);

select*from books;
insert into products values
(5,null,7);