create database movies;

USE MOVIES;

CREATE TABLE MOVIES(
MOVIE_ID VARCHAR(100),
TITTLE VARCHAR(100),
RELEASE_YEAR YEAR,
LANGUAGE VARCHAR(100),
DURATION_MINS INT NOT NULL,
RATING DECIMAL(3,2),
DIRECTOR_ID INT,
FOREIGN KEY (DIRECTOR_ID) REFERENCES DIRECTORS(DIRECTOR_ID)
);

SHOW TABLES;
CREATE TABLE MOVIES(
MOVIE_ID INT PRIMARY KEY auto_increment,
TITTLE VARCHAR(300) NOT NULL,
RELEASE_YEAR YEAR NOT NULL,
GENER varchar (225) NOT NULL,
LANGUAGE VARCHAR(100) default 'TELUGU',
DURATION_MINS INT NOT NULL,
RATING DECIMAL(3,2),
DIRECTOR_ID INT,
FOREIGN KEY (DIRECTOR_ID) REFERENCES DIRECTORS(DIRECTOR_ID)
);

CREATE TABLE DIRECTORS(
DIRECTOR_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100),
DOB DATE,
NATIONALITY VARCHAR(100),
AWARDS TEXT
);

SHOW TABLES;

CREATE TABLE ACTORS(
ACTOR_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(300) NOT NULL, 
DOB DATE,
GENDER CHAR (1),
nationality varchar(100),
debut_year year
);

create table movie_cast(
movie_id int,
actor_id int,
role_name varchar(300),
screen_time_min int not null,
foreign key(movie_id) references movies(movie_id),
foreign key(actor_id) references actors(actor_id),
primary key(movie_id,actor_id)
);

CREATE TABLE BOX_OFFICE(
MOVIE_ID INT, 
BUDGET BIGINT,
BOX_OFFICE_COLLECTION BIGINT,
DOMESTIC_COLLECTION BIGINT, 
INTERNATIONAL_COLLECTION BIGINT,
foreign key(MOVIE_ID) REFERENCES movies(MOVIE_ID),
PRIMARY KEY (MOVIE_ID)
);
